### ISSUE TITLE
[RFE] Limit log messages generated by trafficgen.lua script

### ISSUE THREAD

**Issue by seberm** [atheurer/lua-trafficgen#18]
Hello,
If I run long duration test (and I mean days here), _MoonGen_ logs can reach a very large size (for example 100-200 MB). It would be great if we could **limit** log messages printed by _trafficgen.lua_ script by their severity level.

This severity level could be specified in configuration file:
```
VSPERF {
...
    loggingLevel = "debug",
...
}
```
Possible levels could be {`error, warning, info, debug`}. Default logging level could be
`info`.

**Comment by atheurer** [comment]
I agree.  Most of the log data comes from the stats:update(), which we might be able to suppress or change its interval.  I'll look in to it and come up with something.

**Comment by seberm** [comment]
Please take a look. In the current implementation the logging level must be specified by its number.

Refs:
- [log.lua](https://github.com/libmoon/libmoon/blob/master/lua/log.lua)
- [stats.lua](https://github.com/libmoon/libmoon/blob/master/lua/stats.lua)
