### ISSUE TITLE
Set latency packet size

### ISSUE THREAD

**Issue by k-rister** [atheurer/lua-trafficgen#7]

**Comment by atheurer** [comment]
@k-rister can this be closed now?

**Comment by k-rister** [comment]
I have implemented it in a branch that I have (along with a bunch of other stuff) here:

[https://github.com/k-rister/lua-trafficgen/commits/updates](https://github.com/k-rister/lua-trafficgen/commits/updates)

Setting it to 64B required not using UDP packets and I don't think we have decided if we think that is ok.

**Comment by atheurer** [comment]
If using 64B, lets just use PTP, but print a warning that the latency packets are not UDP.
